#!/usr/bin/env bash
# script that displays content of the file "/etc/passwd" using while loop + IFS
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3s place is protected by the passcode , more info about the user here: 
done < /etc/passwd' > 101-tell_the_story_of_passwd

